### ISSUE TITLE
Xib / Storyboard visualization is broken (reproducible) 

### ISSUE THREAD

**Issue by ataibarkai** [TakeScoop/SwiftyButton#6]
Hi,

First of all, this is an awesome library, thank you so much for your work.

I'm having an issue which I've confirmed on a clean project.

When adding a `SwiftyButton` to a xib/storyboard, all auto-layout behavior becomes broken for the screen on the xib editor. Additionally, the `SwiftyButton` is not rendered as it will appear on the screen (it continues to look like a standard `UIButton`).

During runtime, everything still works fine; only the xib/storyboard editor is broken.

I'm also getting these 2 errors:

```
file:///Users/ataibarkai/Local-Git-Repos/Experiments/SwiftyButtonExperiment/SwiftyButtonExperiment/Base.lproj/Main.storyboard: error: IB Designables: Failed to update auto layout status: dlopen(SwiftyButton.framework, 1): Library not loaded: @rpath/PureLayout.framework/PureLayout
  Referenced from: SwiftyButton.framework
  Reason: image not found

file:///Users/ataibarkai/Local-Git-Repos/Experiments/SwiftyButtonExperiment/SwiftyButtonExperiment/Base.lproj/Main.storyboard: error: IB Designables: Failed to render instance of SwiftyButton: dlopen(SwiftyButton.framework, 1): Library not loaded: @rpath/PureLayout.framework/PureLayout
  Referenced from: SwiftyButton.framework
  Reason: image not found

```

When selecting the module for the custom class on storyboard, I've tried both `SwiftyButton` (autocompleted by Xcode when selecting `SwiftyButton` as the class), and a module with a name identical to my project/target name.

This is reproducible on a clean project, installing `SwiftyButton` using cocoapods (v1.0.1).

**Comment by ataibarkai** [comment]
On a closer look this seems related to this known bug:
http://www.openradar.me/21258097

There's probably nothing that can be done about this on your end (except perhaps document it).

**Comment by ldiqual** [comment]
@ataibarkai Thanks for opening an issue and for saving me some investigation time by linking to the openradar. I'm not completely sure that it's compatible with the latest beta, but can you try this code with the `swift-3.0` branch on Xcode 8 beta 6? Maybe the framework issue is fixed there.
As a side note, I do see that `@IBDesignable` is missing on Xcode 7 but not `@IBInspectable`.

**Comment by RubenSandwich** [comment]
@ldiqual I can confirm that this is still happening on the swift 3 branch with Xcode 8 GM. I wish interface builder gave better error messages mine is just erroring out with the message: "image not found".

**Comment by philippeluickx** [comment]
+1
Working with the latest Xcode 8 and still getting these

file:///project/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for DetailViewController (JEX-9P-axG): dlopen(SwiftyButton.framework, 1): Library not loaded: @rpath/PureLayout.framework/PureLayout
  Referenced from: SwiftyButton.framework
  Reason: image not found

**Comment by ldiqual** [comment]
@philippeluickx How are you integrating SwiftyButton into your project? Seems that you're adding the project manually instead of using cocoapods (which would resolve dependencies automatically).

**Comment by philippeluickx** [comment]
@ldiqual Thanks for getting back so quickly!
I did install it through cocoapods:

```
pod 'SwiftyButton',
:git => 'https://github.com/TakeScoop/SwiftyButton.git',
:branch => 'master'
```

Although I have to say I took over the code from another dev, so I would have to dive a bit more into it to see how the buttons are used.
Any particular reason you suspect manual installation?

**Comment by ldiqual** [comment]
@philippeluickx I'm asking because `SwiftyButton` itself doesn't rely on `PureLayout`, only `SwiftyButton/CustomContent` does. When looking at the podspec, however, it seems we don't explicitly indicate which files need to be compiled for the `SwiftyButton` spec only: https://github.com/TakeScoop/SwiftyButton/blob/master/SwiftyButton.podspec, so maybe cocoapods is adding all the files. I'll look into it more.

**Comment by philippeluickx** [comment]
Seems like there was indeed some residue and the CustomContent was being used in the project too. Cleaned it up and now I am not receiving any issues anymore.
Thanks for the feedback! Not sure if the OP is having a different issue?

**Comment by ldiqual** [comment]
@philippeluickx Yes, the whole `CustomContent` thing needs some work. I'll try to produce a proper version that doesn't rely on PureLayout. It's a bit more complex than just removing the dependency because the example project relies on it, but I'll see what I can do. Thanks for reporting ;)

**Comment by ldiqual** [comment]
@philippeluickx @RubenSandwich Issue https://github.com/TakeScoop/SwiftyButton/issues/5 is now fixed in master, I'm going to publish a new version asap. Thank you!

**Comment by ldiqual** [comment]
Closing this since it seems to be an xcode/framework bug: http://www.openradar.me/21258097.
